import type { Metadata } from "next";
import { Alexandria, Ruwudu, Tajawal } from "next/font/google";
import "./globals.css";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { AddToCartModal } from "../components/AddToCartModal";
import { getAuthContext } from "@/lib/auth";
import { SpeedInsights } from "@vercel/speed-insights/next";

const alexandria = Alexandria({
  variable: "--font-alexandria",
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "600", "700"],
});

const tajawalFont = Tajawal({
  variable: "--font-tajawal",
  subsets: ["arabic", "latin"],
  weight: ["400", "500", "700"],
});

const ruwudu = Ruwudu({
  variable: "--font-ruwudu",
  subsets: ["arabic", "latin"],
  weight: ["500"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  let accountHref = "/auth";
  let accountLabel = "تسجيل الدخول";

  try {
    const { user } = await getAuthContext();
    if (user) {
      accountHref = "/admin";
      accountLabel = "لوحة الإدارة";
    }
  } catch {
    // Keep the account entry usable as a login link when auth is unavailable.
  }

  return (
    <html
      lang="ar"
      className={`${alexandria.className} ${tajawalFont.variable} ${ruwudu.variable} bg-white h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SpeedInsights />
        <Header accountHref={accountHref} accountLabel={accountLabel} />
        <AddToCartModal />
        {children}
        <Footer />
      </body>
    </html>
  );
}
